version: '3.8'
# https://github.com/itzg/docker-minecraft-server#running-a-paper-server

services:
  mc:
    image: itzg/minecraft-server
    environment:
      TYPE: PAPER
      EULA: "true"
      TZ: "Europe/Budapest"
      # valid versions: 1.8.8 1.9.4 1.10.2 1.11.2 1.12.2 1.13.2 1.14.4 1.15.2 1.16.5 1.17.1
      # VERSION: 1.17.1
      SPIGET_RESOURCES: "9089,9089"
      CONSOLE: "false"
    restart: unless-stopped
    tty: true
    stdin_open: true

    ports:
      - 25565:25565
    volumes:
      - ./mc-paper:/data

volumes:
  mc-paper: {}