# docker-compose.yml
version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      # TYPE: VANILLA

      TZ: "Europe/Budapest"
      SERVER_NAME: "Minecraft Server - Berczi"
      MOTD: "Have a nice Crafting"
      CONSOLE: "false"

      DIFFICULTY: "peaceful"

      # https://github.com/itzg/docker-minecraft-server#memory-limit
      MEMORY: 2G

    restart: unless-stopped
    tty: true
    stdin_open: true

      # uncomment this to import a saved game. (put your savegame directory in the saves-to-import directory)
      # WORLD: "/worlds/My-World"

    volumes:
      - ./worlds/vanilla:/worlds:ro
      - ./data/vanilla:/data
