version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      TYPE: PAPER
      EULA: "true"
      # VERSION: 1.17.1
      SPIGET_RESOURCES: "9089"
      CONSOLE: "false"
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    volumes:
      - mc-paper:/data
      - ./data/mc-paper:/data

volumes:
  mc-paper: {}