version: "3.8"
# https://github.com/itzg/docker-minecraft-server#running-a-forge-server

# https://forums.minecraftforge.net/forum/7-releases/
# https://files.minecraftforge.net/net/minecraftforge/forge/

services:
  mc:
    image: itzg/minecraft-server
    environment:
      TYPE: FORGE
      EULA: "true"
      TZ: "Europe/Budapest"
      # DEBUG: "true"

      # Not the latest version
      # VERSION: 1.12.2
      # FORGEVERSION: 14.23.5.2854

    restart: unless-stopped
    tty: true
    stdin_open: true

    ports:
    # expose the Minecraft server port outside of container
    - "25565:25565"

    volumes:
      - ./mc-forge:/data
      - ./mc-forge/mods:/mods:ro

volumes:
  # declared the named volume, but use default/local storage engine
  mc_forge: {}